name: Test
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set go version
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      - name: Run Test
        run: go test -v
